
# 1. Collect Volume Data
$DiskDrives = Get-CimInstance Win32_LogicalDisk | 
    Where-Object DriveType -eq 3 | 
    Select-Object DeviceID, 
                    @{N='SizeGB'; E={[math]::Round($_.Size/1GB, 2)}}, 
                    @{N='FreeGB'; E={[math]::Round($_.FreeSpace/1GB, 2)}}, 
                    @{N='FreePercent'; E={[math]::Round(($_.FreeSpace/$_.Size)*100, 1)}}

# 2. Select drives that require an alert
$LowDiskDrives = $DiskDrives | Where-Object FreePercent -lt 15

if ($LowDiskDrives) {

# 3. Build and send the inlined HTML email body
Email -To 'sysadmin@company.com' -From 'alerts@company.com' `
    -Subject "STORAGE WARNING: $env:COMPUTERNAME Low Disk Space Alert" -Server 'smtp.company.com' -Email {
    EmailBody {
        
        # Banner Header
        EmailLayout {
            EmailLayoutRow {
                EmailLayoutColumn {
                New-HTMLText -Text "<h2 style='margin:0;'>Critical Storage Status Alert</h2>"
                New-HTMLText -Text "System evaluation completed on <b>$env:COMPUTERNAME</b>."
                }
            }
        }

        # Data Grid with Conditional Formatting
        EmailLayoutRow {
            EmailLayoutColumn {
                New-HTMLTable -DataTable $LowDiskDrives -DisablePaging {
                    
                    # Column Formatting
                    New-TableColumnOption -ColumnIndex 0 -Width '20%'
                    New-TableColumnOption -ColumnIndex 3 -Width '20%'
                    
                    # Highlight low disk space in red
                    New-TableCondition -Name 'FreePercent' -ComparisonType number -Operator lt -Value 15 -BackgroundColor '#FFCDD2' -Color '#B71C1C'
                }
            }
        }

        # Footer Section
        EmailLayoutRow {
            EmailLayoutColumn {
                New-HTMLText -Text "<p style='font-size: 11px; color: #777;'>Automated message generated by PSWriteHTML Reporting Engine.</p>"
            }
        }
    }
}

# 3. Deliver Email via SMTP
$SmtpParams = @{
    To         = 'sysadmin@company.com'
    From       = 'alerts@company.com'
    Subject    = "STORAGE WARNING: $env:COMPUTERNAME Low Disk Space Alert"
    Body       = $EmailContent
    BodyAsHtml = $true
    SmtpServer = 'smtp.company.com'
}

Send-MailMessage @SmtpParams